version: "3.8"
services:
    backend-webunity-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "7001:80"
        volumes:
            - .:/app
        networks:
            - backend-webunity
        depends_on:
            - backend-db
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            update_config:
                delay: 10s
                order: start-first
                failure_action: rollback
                monitor: 60s
                max_failure_ratio: 0.3
                parallelism: 1
            resources:
                limits:
                    cpus: "0.25"
                    memory: 768M
                reservations:
                    cpus: "0.25"
                    memory: 768M

    backend-webunity-db:
        image: postgres:16.3
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: unity-db
        ports:
            - "7002:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - backend-webunity
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    cpus: "0.1"
                    memory: 128M
                reservations:
                    cpus: "0.1"
                    memory: 128M

networks:
    backend-webunity:
        driver: overlay

volumes:
    postgres-data:
