version: "3.8"
services:
    backend-app:
        container_name: backend-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "7001:80"
        env_file:
            - .env
        volumes:
            - .:/app
        networks:
            - backend-webunity
        depends_on:
            - backend-db

    backend-db:
        container_name: backend-db
        image: postgres:16.3
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: unity-db
        ports:
            - "7002:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - backend-webunity
        restart: always

networks:
    backend-webunity:
        driver: bridge
