version: "3.8"
services:
    backend-webunity:
        container_name: backend-webunity
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "7001:80"
        volumes:
            - .:/app
        networks:
            - backend-webunity-network
        depends_on:
            - database-webunity

    database-webunity:
        container_name: database-webunity
        image: postgres:16.3
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: unity-db
        ports:
            - "7002:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - backend-webunity-network

networks:
    backend-webunity-network:
        driver: bridge

volumes:
    postgres-data:
